# Generated by Django 5.2.5 on 2025-08-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wed', '0002_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='contenido',
            field=models.CharField(max_length=200),
        ),
    ]
