# Generated by Django 5.2.5 on 2025-08-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wed', '0004_categoria_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ManyToManyField(to='app_wed.categoria'),
        ),
    ]
