# Generated by Django 5.2.5 on 2025-08-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wed', '0005_post_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=70),
        ),
    ]
