# Generated by Django 5.2.5 on 2025-08-25 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wed', '0008_articulo_carrito_carritoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='imagen',
            new_name='imagen_principal',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='talla',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ArticuloVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
                ('talla', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('UNICA', 'Talla Única')], max_length=10)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos/variantes/')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='app_wed.articulo')),
            ],
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_wed.articulovariante'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='categorias',
            field=models.ManyToManyField(related_name='articulos', to='app_wed.categoria_articulo'),
        ),
    ]
