# Generated by Django 5.2.5 on 2025-08-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wed', '0010_pedido_pedidoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
